
services:
  mojdom-api:
    build: .
    container_name: mojdom-api
    ports:
      - "${API_PORT}:${API_PORT}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DEBUG=True
    volumes:
      - .:/app
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:17
    container_name: mojdom-postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: